### ISSUE TITLE
Feeding Animals triggers TimeBetweenB flags

### ISSUE THREAD

**Issue by James-P-Bennett** [ChromMob/BaritoneRemover#1]
When the TimeBetweenB punishment is active, feeding animals can result in players being kicked from the game.
Seems like it should be ignoring those actions.
![image](https://github.com/ChromMob/BaritoneRemover/assets/85420204/56c6588e-977d-4fc5-aac0-fec0dd828af4)

**Comment by NONPLAYT** [comment]
same problem

**Comment by ChromMob** [comment]
Will look into it, somehow missed the issue. Still present on latest build?

**Comment by ChromMob** [comment]
Just verified that this does no longer happen on latest version so closing.
