### ISSUE TITLE
Mind Support ControlPlayers plugin?

### ISSUE THREAD

**Issue by kokqi** [ChromMob/BaritoneRemover#3]
as it flags 
![image](https://github.com/ChromMob/BaritoneRemover/assets/78592988/eba9e510-2b21-4b13-9b07-7e7f424b20e0)

**Comment by kokqi** [comment]
https://www.spigotmc.org/resources/controlplayer-1-8-8-1-20.102987/

**Comment by ChromMob** [comment]
This should not flag. I will try installing the plugin and see myself.

**Comment by ChromMob** [comment]
ControlPlayer fault won't fix.
